// AUTO-GENERATED FILE.
// DO NOT EDIT MANUALLY.
// Generated by client/scripts/generate-mimic-dist-catalog.cjs

export interface MimicDistAsset {
  id: string;
  title: string;
  type: string;
  distPath: string;
  zipFile: string;
  fileCount: number;
  sizeBytes: number;
  size: string;
  hasIndex: boolean;
  files: string[];
}

export const mimicDistCatalog: MimicDistAsset[] = [
  {
    id: "abn-multicompany-dist",
    title: "ABN Multicompany",
    type: "dist",
    distPath: "client/dist",
    zipFile: "abn-multicompany-dist.zip",
    fileCount: 6,
    sizeBytes: 3889001,
    size: "3.7 MB",
    hasIndex: true,
    files:     [
      "assets/index-D2iSTwbr.css",
      "assets/index-DGy1eyoq.js",
      "assets/logo-Bbi31Nv-.png",
      "favicon.svg",
      "icons.svg",
      "index.html"
    ],
  },
];
